### ISSUE TITLE
Up to date build

### ISSUE THREAD

**Issue by lawtonykaps** [DorianScholz/OpenLibre#4]
I have tried to build OpenLibre using Andriod Studio but have come across several problems with newer libraries/Gradle scripts such as "io.tidepool.api:tidepool-api-lib-debug@aar" or Kotlin issues. Can anyone offer me help with how to build the OpenLibre libraries for an Android handset?

**Comment by presquilerecords** [comment]
Hi,
Where are you blocked? Did you manage to build the tidepool lib?

On my side, I can build the apk, but I have this problem at startup:
![image](https://user-images.githubusercontent.com/29518726/68592051-76050c00-0492-11ea-8ef8-7064891fcf57.png)

Launching 'OpenLibre-app' on Pixel API 24.
$ adb shell am start -n "de.dorianscholz.openlibre/de.dorianscholz.openlibre.ui.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 4135 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/ACRA: ACRA is enabled for de.dorianscholz.openlibre, initializing...
I/OpenLibre::OpenLibre: Using saved data path: '/data/user/0/de.dorianscholz.openlibre/files'
D/AndroidRuntime: Shutting down VM
E/ACRA: ACRA caught a RuntimeException for de.dorianscholz.openlibre
    java.lang.RuntimeException: Unable to create application de.dorianscholz.openlibre.OpenLibre: io.realm.exceptions.RealmException: Could not find io.realm.UserDataModuleMediator
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5364)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: io.realm.exceptions.RealmException: Could not find io.realm.UserDataModuleMediator
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:336)
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:310)
        at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:734)
        at de.dorianscholz.openlibre.OpenLibre.setupRealm(OpenLibre.java:136)
        at de.dorianscholz.openlibre.OpenLibre.onCreate(OpenLibre.java:74)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
     Caused by: java.lang.ClassNotFoundException: io.realm.UserDataModuleMediator
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:400)
        at java.lang.Class.forName(Class.java:326)
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:331)
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:310) 
        at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:734) 
        at de.dorianscholz.openlibre.OpenLibre.setupRealm(OpenLibre.java:136) 
        at de.dorianscholz.openlibre.OpenLibre.onCreate(OpenLibre.java:74) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.UserDataModuleMediator" on path: DexPathList[[zip file "/data/app/de.dorianscholz.openlibre-1/base.apk"],nativeLibraryDirectories=[/data/app/de.dorianscholz.openlibre-1/lib/x86, /data/app/de.dorianscholz.openlibre-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:400) 
        at java.lang.Class.forName(Class.java:326) 
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:331) 
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:310) 
        at io.realm.RealmConfiguration$Builder.build(RealmConfiguration.java:734) 
        at de.dorianscholz.openlibre.OpenLibre.setupRealm(OpenLibre.java:136) 
        at de.dorianscholz.openlibre.OpenLibre.onCreate(OpenLibre.java:74) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
D/: HostConnection::get() New Host Connection established 0xa7508800, tid 4165
D/: HostConnection::get() New Host Connection established 0xa7508c80, tid 4170
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 1
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer: Swap behavior 0
D/EGL_emulation: eglCreateContext: 0xa75055a0: maj 2 min 0 rcv 2
Process 4135 terminated.

**Comment by caspervk** [comment]
I got the app built by using the old [Android Studio 3.0](https://developer.android.com/studio/archive) with the following changes to the code:
```patch
Index: build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- build.gradle	(revision c0279e5a6789674ce06bde899bcc184e8832e7ec)
+++ build.gradle	(revision )
@@ -5,9 +5,10 @@
     repositories {
         jcenter()
         mavenCentral()
+        google()
     }
     dependencies {
-        classpath 'com.android.tools.build:gradle:3.0.0-beta2'
+        classpath 'com.android.tools.build:gradle:3.0.0'
         classpath "io.realm:realm-gradle-plugin:3.2.1"
         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
 
@@ -25,6 +26,7 @@
         flatDir { dirs "../../TidepoolAPILib/tidepool-api-lib/build/outputs/aar" }
         jcenter()
         mavenCentral()
+        google()
     }
 }
 
Index: app/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- app/build.gradle	(revision c0279e5a6789674ce06bde899bcc184e8832e7ec)
+++ app/build.gradle	(revision )
@@ -5,7 +5,7 @@
 
 android {
     compileSdkVersion 25
-    buildToolsVersion "25.0.3"
+    buildToolsVersion '26.0.2'
     defaultConfig {
         applicationId "de.dorianscholz.openlibre"
         minSdkVersion 16
```

I built TidepoolAPILib using the newest Android Studio by following its suggestions for fixing gradle etc., but it could probably have been built more easily with Studio 3.0 as well.

I've attached the debug apk in case someone else stumbles upon this in the future: [de.dorianscholz.openlibre-0.2.3-debug.zip](https://github.com/DorianScholz/OpenLibre/files/4010818/de.dorianscholz.openlibre-0.2.3-debug.zip)

**Comment by presquilerecords** [comment]
thanks!

**Comment by Willem3141** [comment]
@presquilerecords Hi! I'm currently stuck building the app (with the newest Android Studio) becauses it crashes on startup with the same exception you were seeing as well. Did you figure out a solution eventually?

(I'll try building with Android Studio 3.0 as well, but I'd really prefer using an up-to-date toolchain ...)

**Comment by DorianScholz** [comment]
Sorry, I have not been able to maintain this anymore for a long time and I am not using the Libre anymore. So I have added a notice to the readme and will archive this repo now.
A more active fork can seems to be here: https://github.com/galekseev/OpenLibre
